application: eggcrackin
version: 1
runtime: go
api_version: go1

handlers:
        - url: /js
          static_dir: build/web/js

        - url: /css
          static_dir: build/web/css

        - url: /main.dart.js
          static_files: build/web/main.dart.js
          upload: build/web/(.*\.js)

        - url: /searchrecipe
          script: _go_app
        - url: /
          static_files: build/web/index.html
          upload: build/web/(.*\.html)
        - url: /recipesearch
          static_files: build/web/index.html
          upload: build/web/(.*\.html)
        - url: /about
          static_files: build/web/index.html
          upload: build/web/(.*\.html)
        - url: /favourites
          static_files: build/web/index.html
          upload: build/web/(.*\.html)
skip_files:
        - ^packages$
        - packages
        - ^tmp$
        - ^(.*/)?\.dart

