name: eggcrackin
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.21
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  browser: ^0.10.0
  test: ^0.12.13+1
  quiver: '>=0.21.4 <0.23.0'
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
